"""
Digital Product Passport -- Lakebase Seeder

Reads JSON files generated by 02_synthetic_data_generator.py and inserts
them into the Lakebase PostgreSQL database. Idempotent: truncates each
table before inserting (respecting FK order).

Usage:
    python 03_seed_lakebase.py

Environment variables:
    LAKEBASE_HOST       Lakebase PostgreSQL hostname
    LAKEBASE_PORT       Port (default: 5432)
    LAKEBASE_DATABASE   Database name (default: dpp)
    LAKEBASE_USER       Database user
    LAKEBASE_PASSWORD   Database password

Alternatively, set LAKEBASE_CONNECTION_STRING for a full DSN.
"""

from __future__ import annotations

import asyncio
import json
import os
import re
import sys
import threading
from pathlib import Path
from typing import Any


def run_async(coro):
    """Run a coroutine to completion even when an event loop is already running.

    Databricks serverless spark_python_task executes inside an active asyncio
    loop, so asyncio.run() raises "cannot be called from a running event loop".
    Running on a fresh loop in a dedicated thread works in both cases.
    """
    box: dict = {}

    def _runner() -> None:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            box["result"] = loop.run_until_complete(coro)
        except BaseException as exc:  # noqa: BLE001
            box["error"] = exc
        finally:
            loop.close()

    thread = threading.Thread(target=_runner)
    thread.start()
    thread.join()
    if "error" in box:
        raise box["error"]
    return box.get("result")

try:
    import asyncpg
except ImportError:
    print(
        "asyncpg is required. Install with: pip install asyncpg",
        file=sys.stderr,
    )
    sys.exit(1)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

def _script_dir() -> Path:
    """Directory containing this script.

    Databricks serverless ``spark_python_task`` does NOT define ``__file__``,
    so fall back to argv[0]. Used to locate the generated data dir.
    """
    try:
        return Path(__file__).resolve().parent
    except NameError:
        return Path(sys.argv[0]).resolve().parent


DATA_DIR = _script_dir() / "data"

# Ordered by FK dependencies (parents first, children last)
TABLE_LOAD_ORDER = [
    "manufacturer",
    "supplier",
    "product_passport",
    "product_origin",
    "product_materials",
    "environmental_impact",
    "compliance_records",
    "circularity_info",
    "disposal_guidelines",
    "passport_audit_log",
]

# Reverse order for truncation (children first)
TABLE_TRUNCATE_ORDER = list(reversed(TABLE_LOAD_ORDER))

# Column mappings: table_name -> list of columns (must match JSON keys)
TABLE_COLUMNS: dict[str, list[str]] = {
    "manufacturer": [
        "manufacturer_id", "name", "country", "registration_number",
        "website", "created_at", "updated_at",
    ],
    "supplier": [
        "supplier_id", "name", "country", "tier", "parent_supplier_id",
        "risk_score", "certifications", "last_audit_date", "active",
        "created_at", "updated_at",
    ],
    "product_passport": [
        "passport_id", "product_id", "gtin", "serial_number",
        "batch_lot_number", "product_name", "product_category",
        "manufacturer_id", "production_date", "production_facility",
        "country_of_origin", "passport_status", "qr_code_url",
        "created_at", "updated_at",
    ],
    "product_origin": [
        "origin_id", "passport_id", "supplier_id", "supply_chain_tier",
        "component_name", "source_country", "source_region",
        "certification", "certification_expiry", "traceability_proof",
    ],
    "product_materials": [
        "material_id", "passport_id", "material_name", "material_category",
        "percentage_by_weight", "recycled_content_pct", "renewable_flag",
        "hazardous_flag", "cas_number", "reach_compliant", "svhc_flag",
    ],
    "environmental_impact": [
        "impact_id", "passport_id", "carbon_footprint_kg",
        "carbon_manufacturing", "carbon_transport", "carbon_use_phase",
        "carbon_end_of_life", "energy_consumption_kwh", "water_usage_liters",
        "lca_methodology", "lca_data_source", "assessment_date", "verified_by",
    ],
    "compliance_records": [
        "compliance_id", "passport_id", "regulation_name",
        "regulation_version", "compliance_status", "certificate_ref",
        "issuing_body", "issue_date", "expiry_date", "document_url", "notes",
    ],
    "circularity_info": [
        "circularity_id", "passport_id", "durability_years",
        "repairability_score", "spare_parts_available", "spare_parts_years",
        "refurbishable", "recycled_content_pct", "recyclability_pct",
        "take_back_program", "second_life_options",
        "state_of_health_pct", "cycle_count", "dynamic_data_updated_at",
    ],
    "disposal_guidelines": [
        "disposal_id", "passport_id", "component_name", "disposal_method",
        "disassembly_steps", "recycling_code", "local_collection_info",
        "special_handling", "weight_kg",
    ],
    "passport_audit_log": [
        "log_id", "passport_id", "table_name", "action",
        "changed_by", "changed_at", "old_values", "new_values",
    ],
}


# ---------------------------------------------------------------------------
# Connection
# ---------------------------------------------------------------------------

def apply_cli_overrides(argv: list[str] | None = None) -> None:
    """Let the bundle pass --instance / --database as task parameters.

    Used by both this seeder and 00_apply_schema so a customer who renames the
    Lakebase instance only edits the bundle variables — no code change.
    """
    import argparse

    ap = argparse.ArgumentParser(add_help=False)
    ap.add_argument("--instance")
    ap.add_argument("--database")
    args, _ = ap.parse_known_args(argv)
    if args.instance:
        os.environ["LAKEBASE_INSTANCE"] = args.instance
    if args.database:
        os.environ["LAKEBASE_DATABASE"] = args.database


def _resolve_runtime_lakebase() -> tuple[str, str, str, str]:
    """Resolve (dns, database, user, oauth_token) using the Databricks runtime
    identity. Used inside jobs/notebooks so no static credentials are needed.

    Uses the REST API (not the SDK database client) for compatibility with
    older DBR images — matches the bronze ingestion pipeline.
    """
    import uuid

    import requests
    from databricks.sdk import WorkspaceClient

    instance = os.environ.get("LAKEBASE_INSTANCE", "dpp-passport")
    database = os.environ.get("LAKEBASE_DATABASE", "databricks_postgres")

    w = WorkspaceClient()
    host = w.config.host.rstrip("/")
    headers = w.config.authenticate()  # {"Authorization": "Bearer <token>"}

    inst = requests.get(
        f"{host}/api/2.0/database/instances/{instance}",
        headers=headers, timeout=30,
    )
    inst.raise_for_status()
    dns = inst.json()["read_write_dns"]

    cred = requests.post(
        f"{host}/api/2.0/database/credentials",
        headers=headers, timeout=30,
        json={"request_id": str(uuid.uuid4()), "instance_names": [instance]},
    )
    cred.raise_for_status()
    token = cred.json()["token"]

    me = requests.get(
        f"{host}/api/2.0/preview/scim/v2/Me", headers=headers, timeout=30,
    )
    me.raise_for_status()
    user = me.json()["userName"]

    return dns, database, user, token


_PLACEHOLDER_RE = re.compile(r"%s")


def _to_pg(query: str) -> str:
    """Convert psycopg-style %s placeholders to asyncpg's positional $1, $2, …"""
    counter = {"n": 0}

    def repl(_match: re.Match) -> str:
        counter["n"] += 1
        return f"${counter['n']}"

    return _PLACEHOLDER_RE.sub(repl, query)


# The synthetic data carries dates/timestamps as ISO strings, UUIDs as strings,
# and numerics as floats. Register text-format codecs so asyncpg sends them with
# the correct PG type but in text form (the server parses) — this mirrors
# psycopg's lenient text protocol so the generator's output flows through as-is.
_TEXT_CODEC_TYPES = ("uuid", "date", "timestamp", "timestamptz", "json", "jsonb")


async def _init_codecs(conn: asyncpg.Connection) -> None:
    for type_name in _TEXT_CODEC_TYPES:
        await conn.set_type_codec(
            type_name, schema="pg_catalog",
            encoder=lambda v: v, decoder=lambda v: v, format="text",
        )
    await conn.set_type_codec(
        "numeric", schema="pg_catalog",
        encoder=lambda v: str(v), decoder=lambda v: v, format="text",
    )


async def _connect() -> asyncpg.Connection:
    """Connect to Lakebase (asyncpg). Two paths:

      1. LAKEBASE_HOST + LAKEBASE_PASSWORD — explicit native login (local).
      2. Databricks runtime — self-authenticate with a short-lived OAuth token
         from the job's identity (no secrets). This is what the bundle's setup
         job uses, so customer redeploys need zero credential wiring.
    """
    if os.environ.get("LAKEBASE_HOST"):
        conn = await asyncpg.connect(
            host=os.environ["LAKEBASE_HOST"],
            port=int(os.environ.get("LAKEBASE_PORT", "5432")),
            database=os.environ.get("LAKEBASE_DATABASE", "databricks_postgres"),
            user=os.environ["LAKEBASE_USER"],
            password=os.environ["LAKEBASE_PASSWORD"],
            ssl=True,
        )
    else:
        dns, database, user, token = _resolve_runtime_lakebase()
        conn = await asyncpg.connect(
            host=dns, port=5432, database=database, user=user,
            password=token, ssl=True,
        )
    await _init_codecs(conn)
    return conn


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_json(table_name: str) -> list[dict[str, Any]]:
    """Load a JSON file for the given table name."""
    path = DATA_DIR / f"{table_name}.json"
    if not path.exists():
        print(f"  SKIP {table_name} (no data file)")
        return []
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def prepare_value(value: Any, column: str) -> Any:
    """Convert Python values to what asyncpg sends correctly given the text
    codecs in _init_codecs: JSONB columns as JSON strings, lists as native
    arrays, everything else as-is."""
    if value is None:
        return None
    if column in ("old_values", "new_values"):
        return value if isinstance(value, str) else json.dumps(value)
    if isinstance(value, list):  # TEXT[] -> native asyncpg array
        return value
    if isinstance(value, dict):
        return json.dumps(value)
    return value


async def insert_table(
    conn: asyncpg.Connection,
    table_name: str,
    records: list[dict[str, Any]],
) -> int:
    """Insert records into a Lakebase table. Returns count inserted."""
    if not records:
        return 0

    columns = TABLE_COLUMNS[table_name]
    placeholders = ", ".join(["%s"] * len(columns))
    col_names = ", ".join(columns)
    sql = _to_pg(f"INSERT INTO dpp.{table_name} ({col_names}) VALUES ({placeholders})")

    rows = [
        tuple(prepare_value(record.get(col), col) for col in columns)
        for record in records
    ]
    await conn.executemany(sql, rows)
    return len(rows)


async def truncate_tables(conn: asyncpg.Connection) -> None:
    """Truncate all tables in reverse FK order.

    TRUNCATE does not fire the row-level AFTER INSERT/UPDATE/DELETE audit
    triggers, so no trigger suppression is needed. (We avoid
    `SET session_replication_role`, which is superuser-only and not available
    to the Lakebase app/job role.)
    """
    for table in TABLE_TRUNCATE_ORDER:
        await conn.execute(f"TRUNCATE TABLE dpp.{table} CASCADE;")
        print(f"  Truncated dpp.{table}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

async def _seed_async() -> None:
    """Seed all Lakebase tables from generated JSON data (file-based, local)."""
    apply_cli_overrides()
    print("=" * 60)
    print("DPP Lakebase Seeder")
    print("=" * 60)

    if not DATA_DIR.exists():
        print(f"ERROR: Data directory not found: {DATA_DIR}")
        print("Run 02_synthetic_data_generator.py first.")
        sys.exit(1)

    conn = await _connect()
    try:
        async with conn.transaction():
            print("\nTruncating existing data...")
            await truncate_tables(conn)
            print("\nLoading data...")
            total = 0
            for table_name in TABLE_LOAD_ORDER:
                records = load_json(table_name)
                if records:
                    count = await insert_table(conn, table_name, records)
                    print(f"  Inserted {count:>5} rows into dpp.{table_name}")
                    total += count
        print(f"\nTotal rows inserted: {total}")
        print("Done.")
    finally:
        await conn.close()


def main() -> None:
    run_async(_seed_async())


if __name__ == "__main__":
    main()
